### ISSUE TITLE
New Entries not being added/updated

### ISSUE THREAD

**Issue by mark-chief** [Rias500/craft-scout#40] opened 2018-10-29 09:34 UTC
This _may_ of happened when I updated to the latest version.

It looks like when i am creating a new entry it adds it to Agolia, but then removes it. E.g, I created the entry in the `websitePages` section and its ID is `1895`, see below logs where it appears to add, remove, add and then remove it.

Here is my queue.log:
```
2018-10-29 09:27:11 [-][1][-][info][craft\queue\QueueLogBehavior::beforeExec]  [16862] Updating element slugs and URIs (attempt: 1) - Started
2018-10-29 09:27:11 [-][1][-][info][craft\queue\QueueLogBehavior::afterExec]  [16862] Updating element slugs and URIs (attempt: 1) - Done (time: 0.023s)
2018-10-29 09:27:11 [-][1][-][info][craft\queue\QueueLogBehavior::beforeExec]  [16863] Adding element 1_1895 to index (attempt: 1) - Started
2018-10-29 09:27:11 [-][1][-][info][craft\queue\QueueLogBehavior::afterExec]  [16863] Adding element 1_1895 to index (attempt: 1) - Done (time: 0.070s)
2018-10-29 09:27:11 [-][1][-][info][craft\queue\QueueLogBehavior::beforeExec]  [16864] Removing element 1_1895 from index (attempt: 1) - Started
2018-10-29 09:27:11 [-][1][-][info][craft\queue\QueueLogBehavior::afterExec]  [16864] Removing element 1_1895 from index (attempt: 1) - Done (time: 0.047s)
2018-10-29 09:27:11 [-][1][-][info][craft\queue\QueueLogBehavior::beforeExec]  [16865] Adding element 1_1895 to index (attempt: 1) - Started
2018-10-29 09:27:11 [-][1][-][info][craft\queue\QueueLogBehavior::afterExec]  [16865] Adding element 1_1895 to index (attempt: 1) - Done (time: 0.061s)
2018-10-29 09:27:11 [-][1][-][info][craft\queue\QueueLogBehavior::beforeExec]  [16866] Removing element 1_1895 from index (attempt: 1) - Started
2018-10-29 09:27:11 [-][1][-][info][craft\queue\QueueLogBehavior::afterExec]  [16866] Removing element 1_1895 from index (attempt: 1) - Done (time: 0.048s)
2018-10-29 09:27:11 [-][1][-][info][craft\queue\QueueLogBehavior::beforeExec]  [16867] Deleting stale template caches (attempt: 1) - Started
2018-10-29 09:27:13 [-][1][-][info][craft\queue\QueueLogBehavior::afterExec]  [16867] Deleting stale template caches (attempt: 1) - Done (time: 1.649s)
```
Here is my scout config:

```
<?php

return [
    "sync" => true,
    "application_id" => "xxx",
    "admin_api_key" => "xxxxxxxx",
    "mappings" => [
        [
            'indexName' => 'removedfordemo',
            'elementType' => \craft\elements\Entry::class,
            'criteria' => [
                'section' => 'websitePages',
                'type' => 'websitePages'
            ],            
            'transformer' => function(craft\elements\Entry $entry) {
	            
				Craft::$app->getConfig()->getGeneral()->generateTransformsBeforePageLoad = true;
	            
			    // Begin defining the response data for this entry
			    $data = [
			        'title' => $entry->title,
			        'slug' => $entry->url,
			        //'textArea' => $entry->textArea,
    			    'textArea' => ! empty($entry->textArea) ? (string) $entry->textArea : 'No preview text available',
    			    //'heroBanner' => ! empty($entry->heroBanner->one()->) ? (string) $entry->heroBanner->one()->url : '/images/site/mc-placeholder-480x324.jpg',
                    'status' => $entry->status           
			    ];
			    
			    // Get the first asset in a "heroImage" Assets field (if there is one)
			    $heroBanner = $entry->heroBanner->one();
		        $data['heroBanner'] = $heroBanner ? $heroBanner->getUrl('mailchimpThumbnails') : '/images/site/mc-placeholder-480x324.jpg';
			    return $data;	            
			},
        ],
        [
            'indexName' => 'removedfordemo',
            'elementType' => \craft\elements\Entry::class,
            'criteria' => [
                'section' => 'pupilsWork',
            ],            
            'transformer' => function(craft\elements\Entry $entry) {
				Craft::$app->getConfig()->getGeneral()->generateTransformsBeforePageLoad = true;
			    $data = [
			        'title' => "Pupils Work: $entry->title",
			        'slug' => $entry->url,
    			    'textArea' => ! empty($entry->textArea) ? (string) $entry->textArea : 'No preview text available',
                    'status' => $entry->status           
			    ];
			    $heroBanner = $entry->overviewImage->one();
		        $data['heroBanner'] = $heroBanner ? $heroBanner->getUrl('mailchimpThumbnails') : '/images/site/mc-placeholder-480x324.jpg';
			    return $data;	            
			},
        ],
    ],
];
```

**Comment by marksimons** [comment] 2018-11-26 20:00
Appreciate any help on this if it is being supported still? Thanks

**Comment by Rias500** [comment] 2018-11-26 20:44
Hi @marksimons, yes it’s still being supported, though work has been very busy lately so I don’t have the time to work on fixes at the moment. That’s why this package is free, MIT licensesed and comes without support.

If you find the issue in the meantime and are able to fix it yourself, I’d appreciate a PR, if not I’ll get to this issue when I find the time.

**Comment by mark-chief** [comment] 2018-11-26 20:46
Ok. Appreciate that. 

Is there any way I can downgrade the version to the previous as it worked then?

**Comment by Rias500** [comment] 2018-11-26 20:48
You can request a different version by changing it in `composer.json` and running `composer update`

**Comment by Rias500** [comment] 2018-12-03 09:58
@mark-chief I can't seem to reproduce this, are you adding both mappings to the same index? Or are they different indices? Because in your config it says `removedfordemo` on both

**Comment by marksimons** [comment] 2018-12-03 10:05
@Rias500 Hi, they are being added to the same Index, sorry that wasn't very clear in my example!

**Comment by mark-chief** [comment] 2018-12-03 10:06
@Rias500  Hi, they are being added to the same Index, sorry that wasn't very clear in my example!

**Comment by Rias500** [comment] 2018-12-03 10:17
So I've copied your mappings into my own project, and added the fields to have an example and they're both added to the index:

![image](https://user-images.githubusercontent.com/3626559/49367328-10d66180-f6ec-11e8-921a-28d4ca5ebf2a.png)

I've also tried it with multiple types and that works fine as well.

Could you update to 1.0.2 and try again? There have been a few fixes in the meantime that might resolve your issue.

**Comment by Rias500** [comment] 2018-12-12 13:44
Closing this for now, you can always reopen if this issue still persists and you have more information.

**Closed by Rias500** 2018-12-12 13:44 UTC
