### ISSUE TITLE
Deleted items not being removed since update

### ISSUE THREAD

**Issue by JonnyTurnerUK** [Rias500/craft-scout#55] opened 2019-02-19 10:46 UTC
Hey @Rias500 - we updated your plugin (thanks!) the other day and we've noticed that deleted entries are not being removed from Algolia so our entry count and Algolia count is off. Any chance you can help sort? We use FeedMe to import stock and has been working perfectly in hand with Scout.

**Comment by johnj24** [comment] 2019-02-19 15:37
We too have noticed that disabled entries are being left in the Algolia index. I imagine these are similar issues.

**Comment by Rias500** [comment] 2019-02-27 09:21
Indeed a regression caused by a change in the previous release, should be fixed in 1.1.3

**Comment by JonnyTurnerUK** [comment] 2019-02-27 09:22
Awesome, thanks @Rias500

**Closed by Rias500** 2019-02-27 09:21 UTC
